fs = require 'fs'
{exec, spawn} = require 'child_process'

task 'build', ->
  exec 'coffee --compile --output lib/ src/', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr

task 'test', ->
  process.env['NODE_PATH'] += ':src'
  options = ['spec', '--coffee']
  jasmine = spawn 'jasmine-node', options
  jasmine.stdout.on 'data', (data) -> console.log data.toString()
  jasmine.stderr.on 'data', (data) -> console.log data.toString()
  jasmine.on 'exit', (status) -> console.log "OK" if status is 0

